# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
# This job was moved to .github/workflows/release.yml
# Keeping a no-op as CircleCI might be needed for previous versions
# so can't be disabled yet
jobs:
  build:
    docker:
      # use the same build image as we use for metabuildbot
      - image: buildbot/metabbotcfg@sha256:f546230546faf3a0397b7a7f8f75559bb82abe3404b1fb726e10ffb4dba96af9
    working_directory: ~/repo
    environment:
      # Needed to ignore specific warns, otherwise, it'll warn a generic message
      SQLALCHEMY_WARN_20: 1

    steps:
      - run:
          name: no-op
          command: echo no-op

workflows:
  version: 2
