[build-system]
requires = [
    "setuptools>=61.3",
]
# Create a dummy backend, which is overkill for our needs
# but we NEED to add '.' to PYTHONPATH to access buildbot_worker.version
build-backend = "buildbot_backend"
backend-path = ["_custom_build", "."]

[project]
name = "buildbot-worker"
authors = [
    { name = "Brian Warner", email = "warner-buildbot@lothar.com" },
]
maintainers = [
    { name = "Dustin J. Mitchell", email = "dustin@v.igoro.us" },
]
description = "Buildbot Worker Daemon"
readme = { text = "See the 'buildbot' package for details", "content-type" = "text/plain" }
license = "GPL-2.0-or-later"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: No Input/Output (Daemon)",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Testing",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dynamic = [
    "version",
    "scripts",
]

dependencies = [
    'twisted >= 21.2.0',
    'autobahn >= 0.16.0',
    'msgpack >= 0.6.0',
    # buildbot_worker_windows_service needs pywin32
    'pywin32; platform_system=="Windows"'
]

[project.optional-dependencies]
# Unit test hard dependencies.
test = [
    'psutil',
]

[project.urls]
Homepage = "http://buildbot.net/"

[tool.aliases]
test = "trial -m buildbot_worker"

[tool.setuptools]
include-package-data=false
